# Generated by Django 4.2.15 on 2024-08-25 16:23

from django.db import migrations, models
import nour.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=nour.models.image_upload)),
            ],
        ),
    ]
