# Generated by Django 4.2.15 on 2024-08-25 20:22

from django.db import migrations, models
import nour.models


class Migration(migrations.Migration):

    dependencies = [
        ('nour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=nour.models.image_upload)),
                ('specialization', models.CharField(max_length=100)),
            ],
        ),
    ]
