# Generated by Django 4.2.15 on 2024-08-25 21:43

from django.db import migrations, models
import nour.models


class Migration(migrations.Migration):

    dependencies = [
        ('nour', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_left',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=nour.models.image_upload)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Price_right',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=nour.models.image_upload)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
