# Generated by Django 4.2.15 on 2024-08-25 21:59

from django.db import migrations, models
import nour.models


class Migration(migrations.Migration):

    dependencies = [
        ('nour', '0004_price_left_price_right'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=nour.models.image_upload)),
            ],
        ),
    ]
