# Generated by Django 4.2.15 on 2024-08-26 17:04

from django.db import migrations, models
import nour.models


class Migration(migrations.Migration):

    dependencies = [
        ('nour', '0005_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=nour.models.image_upload)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
