# Generated by Django 4.2.15 on 2024-08-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nour', '0007_eye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nails',
            name='price',
        ),
    ]
